apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theta-kustomize-maintenance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lyhovseab/argocd-apps.git
    targetRevision: HEAD
    path: kustomize/maintenance/overlays/theta
  destination:
    server: https://kubernetes.default.svc
    namespace: theta
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
