server {
    listen 8080;
    server_name  _;
    location / {
        add_header Cache-Control "private, no-cache, no-store, must-revalidate" always;
        error_page 405 500 502 503 504 =503 $uri;
        try_files $uri /index.html =503;
    }
    root  /usr/share/nginx/html;
    index  index.html;
}
