apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- onlyoffice-token-secret.yaml
- onlyoffice-deployment.yaml
- onlyoffice-service.yaml
- onlyoffice-middleware.yaml
- onlyoffice-ingress.yaml


labels:
  - pairs:
      app.kubernetes.io/name: onlyoffice-docserver
      app.kubernetes.io/instance: onlyoffice-docserver
      app.kubernetes.io/component: onlyoffice-docserver
    includeSelectors: true

commonAnnotations:
  app.kubernetes.io/name: kustomize
